spring.application.name=ecommerce
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.hibernate.ddl-auto=update
project.image=images
spring.app.jwtSecret=fjiagnsalvbsalvsedsjfiesgibisghacnaljgjegiocnsghaugebgcjxklfdgh
spring.app.jwtExpirationMs=3000000
logging.level.org.springframeword=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.security=DEBUG
logging.level.com.qumengdie.ecommerce=DEBUG