spring.application.name=ecommerce
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.hibernate.ddl-auto=update
project.image=images
spring.app.jwtSecret=fjiagnsalvbsalvsedsjfiesgibisghacnaljgjegiocnsghaugebgcjxklfdgh
spring.app.jwtExpirationMs=3000000
logging.level.org.springframeword=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.security=DEBUG
logging.level.com.qumengdie.ecommerce=DEBUG
spring.app.jwtCookieName=myCookie
#MySQL
#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
#spring.datasource.username=root
#spring.datasource.password=MySQLPassword897
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#PostgresSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=mypostgresqlpass897
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#frontend url
frontend.url=http://localhost:5173
#image url
image.base.url=http://localhost:8080/images
